FROM node:lts-alpine3.22 AS base

WORKDIR /app

COPY package*.json ./
COPY turbo.json ./
COPY apps/web/package.json ./apps/web/package.json
COPY packages/core/package.json ./packages/core/package.json

COPY . .

# Variável pública para o Next
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN npm i

# Build somente do web
RUN npm run build -w web

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "run", "start", "--workspace", "web"]